package com.simplegamegen.sudoku.words

/** Bundled English content; clues are original and require no external puzzle service. */
internal object WordCatalog {
    val moreClues = listOf(
        "ORANGE" to "A citrus fruit whose name is also a color",
        "BANANA" to "A curved fruit with a peel that turns yellow",
        "CHERRY" to "A small red fruit with a single hard stone",
        "CARROT" to "An orange root vegetable",
        "POTATO" to "A starchy tuber often mashed or baked",
        "TOMATO" to "A red fruit often used in pasta sauce",
        "CHEESE" to "A food made by pressing or aging milk curds",
        "BUTTER" to "A spread made by churning cream",
        "NOODLE" to "A long thin strip of pasta",
        "PEPPER" to "A spice commonly paired with salt",
        "COOKIE" to "A small sweet baked treat",
        "HONEY" to "A sweet food made by bees",
        "PEACH" to "A fruit with fuzzy skin and a hard stone",
        "GRAPE" to "A small fruit that grows in bunches on a vine",
        "MELON" to "A large juicy fruit with a thick rind",
        "BERRY" to "A small juicy fruit such as a blueberry",
        "FOREST" to "A large area covered with trees",
        "DESERT" to "A region that receives very little rain",
        "VALLEY" to "Low land between hills or mountains",
        "ISLAND" to "Land surrounded by water",
        "MEADOW" to "A grassy field often filled with wildflowers",
        "STREAM" to "A small flowing body of water",
        "CANYON" to "A deep valley with steep sides",
        "GLACIER" to "A huge mass of ice that moves slowly over land",
        "VOLCANO" to "An opening in Earth's crust that can release lava",
        "MOUNTAIN" to "A very high natural rise in the land",
        "WATERFALL" to "A stream dropping over a cliff",
        "SUNRISE" to "The moment the sun appears above the morning horizon",
        "RAINBOW" to "An arc of colors made by sunlight and water drops",
        "THUNDER" to "The sound that follows a flash of lightning",
        "BREEZE" to "A gentle wind",
        "FROST" to "A thin coating of ice crystals on a cold surface",
        "BEACH" to "A sandy or pebbly shore",
        "STONE" to "A small piece of rock",
        "SHELL" to "The hard outer covering of a clam",
        "TRAIL" to "A path used for walking through the countryside",
        "RABBIT" to "A small mammal with long ears and a short tail",
        "TURTLE" to "A reptile protected by a hard shell",
        "DOLPHIN" to "A marine mammal known for its curved dorsal fin",
        "PENGUIN" to "A flightless seabird that swims with flipperlike wings",
        "GIRAFFE" to "An African animal with a very long neck",
        "ELEPHANT" to "A large mammal with a trunk",
        "BUTTERFLY" to "An insect that develops from a caterpillar",
        "SQUIRREL" to "A bushy-tailed rodent that often gathers nuts",
        "HAMSTER" to "A small pet rodent with roomy cheek pouches",
        "PARROT" to "A bird known for copying human speech",
        "BADGER" to "A burrowing mammal often marked with facial stripes",
        "FALCON" to "A bird of prey known for fast flight",
        "WHALE" to "A large marine mammal that breathes through a blowhole",
        "ZEBRA" to "An African relative of the horse with black and white stripes",
        "CAMEL" to "A desert mammal with one or two humps",
        "PANDA" to "A black-and-white bear that mainly eats bamboo",
        "ROCKET" to "A vehicle propelled by gases expelled from an engine",
        "GALAXY" to "A vast collection of stars, gas and dust",
        "METEOR" to "A streak of light made by a space rock entering the atmosphere",
        "SATURN" to "The planet famous for its bright rings",
        "NEPTUNE" to "The outermost of the eight planets in our solar system",
        "ASTEROID" to "A rocky object orbiting the sun, smaller than a planet",
        "TELESCOPE" to "An instrument used to see distant objects in the sky",
        "SATELLITE" to "An object that travels around a planet or another larger body",
        "COMPASS" to "A navigation tool with a needle that points north",
        "BRIDGE" to "A structure carrying a path over a river or road",
        "TUNNEL" to "A passage built through or under an obstacle",
        "AIRPORT" to "A place where airplanes take off and land",
        "BICYCLE" to "A two-wheeled vehicle powered by pedals",
        "SUITCASE" to "A handled case for carrying clothes on a trip",
        "PASSPORT" to "An official document used for international travel",
        "BACKPACK" to "A bag carried on the back with shoulder straps",
        "LANTERN" to "A portable lamp with a protective case",
        "UMBRELLA" to "A folding canopy held overhead to keep off rain",
        "LIBRARY" to "A place where books can be borrowed",
        "CALENDAR" to "A chart showing the days, weeks and months",
        "KEYBOARD" to "A set of keys used to type into a computer",
        "SCISSORS" to "A cutting tool with two pivoting blades",
        "PAINTING" to "A picture made with colored pigment and a brush",
        "TRUMPET" to "A brass instrument with three valves and a flared bell",
        "VIOLIN" to "A four-stringed instrument played with a bow under the chin",
        "GUITAR" to "A stringed instrument commonly strummed with fingers or a pick",
        "RHYTHM" to "The pattern of beats in music",
        "MELODY" to "A sequence of notes heard as a tune",
    )

    // Each theme has more words than even the largest puzzle needs, so new
    // puzzles vary their answer lists as well as their layouts.
    val searches: List<Pair<String, List<String>>> = listOf(
        "Nature" to "RIVER OCEAN TREE LEAF RAIN CLOUD ROOT SEED ROSE GRASS FOREST DESERT VALLEY ISLAND MEADOW STREAM CANYON GLACIER MOUNTAIN WATERFALL",
        "Animals" to "TIGER HORSE OTTER EAGLE ROBIN SNAIL WHALE ZEBRA CAMEL PANDA RABBIT TURTLE DOLPHIN PENGUIN GIRAFFE ELEPHANT BUTTERFLY SQUIRREL HAMSTER PARROT",
        "Space" to "PLANET STAR MOON COMET ORBIT SPACE MARS VENUS SUN EARTH PLUTO SOLAR ROCKET GALAXY METEOR SATURN NEPTUNE ASTEROID TELESCOPE SATELLITE",
        "Everyday" to "BOOK PAPER PENCIL CLOCK MUSIC PIANO CHAIR TABLE BRUSH PHONE GLASS PLATE SPOON TOWEL WINDOW MIRROR BLANKET PILLOW BASKET BUTTON",
        "Food" to "APPLE PEAR BREAD GRAPE MELON BERRY HONEY RICE SALAD SOUP ORANGE BANANA CHERRY CARROT POTATO TOMATO CHEESE BUTTER NOODLE COOKIE",
        "Travel" to "TRAIN BOAT ROAD WHEEL MAP HOTEL BUS TAXI PLANE SHIP COMPASS BRIDGE TUNNEL AIRPORT BICYCLE SUITCASE PASSPORT BACKPACK TICKET JOURNEY",
        "Sports" to "BALL GOAL TEAM RACE GOLF TENNIS SOCCER HOCKEY RUGBY RELAY TRACK COURT SCORE SKATE SWIM CYCLING RUNNING ARCHERY CRICKET BASEBALL",
        "Music" to "NOTE SONG BEAT DRUM FLUTE PIANO HARP CHOIR SCALE TUNE GUITAR VIOLIN TRUMPET RHYTHM MELODY CONCERT SINGER CYMBAL ORGAN ORCHESTRA",
        "Ocean" to "WAVE TIDE REEF KELP CORAL SHARK WHALE SHELL BEACH COAST SAND CRAB SEAL PEARL DOLPHIN OCTOPUS STARFISH SEAHORSE LOBSTER SEAWATER",
        "Weather" to "RAIN SNOW WIND CLOUD FROST STORM SLEET HAIL FOG SUN HEAT DRY HUMID BREEZE THUNDER RAINBOW LIGHTNING BLIZZARD FORECAST DRIZZLE",
        "Garden" to "ROSE SEED SOIL ROOT LEAF STEM GRASS HERB VINE BULB MOSS FERN TULIP DAISY ORCHID FLOWER COMPOST SHOVEL SPROUT WATERING",
        "Science" to "ATOM CELL LIGHT HEAT FORCE WAVE GENE LASER PRISM PLANT SOLID LIQUID ENERGY MAGNET GRAVITY OXYGEN CARBON CIRCUIT ELECTRON MOLECULE",
    ).map { (title, words) -> title to words.split(' ') }
}
