package com.simplegamegen.sudoku.wordplay

import com.simplegamegen.sudoku.wordplay.ThreadRule.Anagram
import com.simplegamegen.sudoku.wordplay.ThreadRule.Compound
import com.simplegamegen.sudoku.wordplay.ThreadRule.Hidden
import com.simplegamegen.sudoku.wordplay.ThreadRule.Tag

/**
 * English material for Common Threads, written for this app. Tags list generously every word a
 * player could argue belongs ([Tag.also]), so the one-answer check errs on the strict side.
 */
object EnglishThreads {
    private fun w(text: String): Set<String> = text.trim().split(Regex("\\s+")).toSet()

    private val fish = w("SALMON TROUT COD TUNA CARP PIKE BASS SOLE PERCH SHARK EEL HERRING PLAICE HADDOCK MACKEREL SARDINE MINNOW")
    private val birds = w("EAGLE ROBIN CROW OWL SWAN DUCK GOOSE HAWK WREN DOVE PARROT PENGUIN TURKEY HEN CRANE SWIFT JAY FINCH LARK PIGEON RAVEN STORK HERON")
    private val insects = w("ANT BEE WASP FLY MOTH GNAT FLEA BEETLE CRICKET TERMITE LOCUST APHID MIDGE")
    private val farm = w("COW PIG HORSE SHEEP GOAT HEN DUCK GOOSE DONKEY TURKEY LLAMA BULL OX RAM EWE LAMB CALF FOAL CHICK PIGLET")
    private val wild = w("LION TIGER BEAR WOLF FOX DEER ZEBRA GIRAFFE HIPPO RHINO MONKEY ELEPHANT CAMEL OTTER BADGER HARE RABBIT MOLE SEAL WHALE " +
        "BAT RAT MOUSE SQUIRREL MOOSE ELK YAK EMU GNU APE PUMA STOAT STAG BOAR TOAD FROG NEWT SNAKE LIZARD SNAIL CRAB TEAL")

    /** Every animal the rules know, for hidden words and anagrams. */
    private val animals = fish + birds + insects + farm + wild + w("CAT DOG ASP RAY EEL HOG MARE COLT KID PUP CUB")

    private val bodyParts = w("ARM LEG HAND FOOT HEAD NOSE EAR EYE KNEE CHIN NECK BACK HIP LIP TOE SHIN PALM CALF HEEL THUMB ELBOW WRIST ANKLE CHEST " +
        "BROW JAW GUM RIB SHOULDER FINGER TOOTH TONGUE HEART LUNG LIVER SKIN HAIR NAIL SPINE")

    private val numbers = w("ONE TWO THREE FOUR FIVE SIX SEVEN EIGHT NINE TEN ELEVEN TWELVE")

    private val tags = listOf(
        Tag("FRUIT", "Fruits", w("APPLE BANANA CHERRY GRAPE LEMON LIME MANGO MELON ORANGE PEACH PEAR PLUM KIWI FIG DATE APRICOT"),
            also = w("OLIVE TOMATO PUMPKIN SQUASH PEPPER NUT COCONUT")),
        Tag("COLOR", "Colors", w("RED BLUE GREEN YELLOW PURPLE ORANGE PINK BROWN BLACK WHITE GRAY"),
            also = w("LIME PLUM PEACH CHERRY LEMON SALMON GOLD SILVER COPPER BRONZE AMBER JADE RUBY EMERALD SAPPHIRE OLIVE CREAM MINT ROSE VIOLET " +
                "LILAC TAN FAWN IVORY CORAL TEAL NAVY SKY CHOCOLATE COFFEE SAND STONE SLATE CHERRY MAROON CRIMSON MUSTARD GINGER HAZEL ASH PEARL")),
        Tag("FISH", "Fish", fish - "SHARK" - "EEL", also = w("SHARK EEL RAY WHALE CRAB SQUID")),
        Tag("BIRD", "Birds", birds - "TURKEY" - "HEN", also = w("TURKEY HEN CHICK EMU TEAL ROOK KITE SWALLOW TIT")),
        Tag("INSECT", "Insects", insects, also = w("SPIDER BUG")),
        Tag("FARM", "Farm animals", w("COW PIG HORSE SHEEP GOAT HEN DUCK GOOSE DONKEY TURKEY LLAMA BULL"), also = farm + w("RABBIT DOG CAT")),
        Tag("WILD", "Wild animals", w("LION TIGER BEAR WOLF FOX DEER ZEBRA GIRAFFE HIPPO RHINO MONKEY ELEPHANT CAMEL OTTER BADGER"),
            also = wild + birds + fish + insects),
        Tag("BODY", "Parts of the body", w("ARM LEG HAND FOOT HEAD NOSE EAR EYE KNEE CHIN NECK HIP LIP TOE SHIN HEEL THUMB ELBOW WRIST ANKLE"),
            also = bodyParts),
        Tag("TREE", "Trees", w("OAK ASH ELM PINE PALM BIRCH MAPLE WILLOW CEDAR FIR YEW BEECH SPRUCE HAZEL LARCH"), also = w("OLIVE APPLE CHERRY PLUM PEAR FIG LIME")),
        Tag("WEATHER", "Weather", w("RAIN SNOW HAIL WIND FOG MIST SLEET STORM FROST THUNDER DRIZZLE"), also = w("SUN CLOUD ICE HEAT SHOWER GALE BREEZE")),
        Tag("INSTRUMENT", "Instruments", w("PIANO DRUM FLUTE HARP VIOLIN CELLO GUITAR TUBA OBOE BANJO TRUMPET CLARINET"),
            also = w("ORGAN BASS HORN TRIANGLE BELL RECORDER SAXOPHONE CYMBAL")),
        Tag("SHAPE", "Shapes", w("CIRCLE SQUARE TRIANGLE OVAL CUBE SPHERE CONE RECTANGLE HEXAGON PYRAMID"), also = w("STAR HEART DIAMOND CROSS ARROW RING")),
        Tag("GEM", "Gems", w("RUBY PEARL OPAL JADE DIAMOND EMERALD SAPPHIRE TOPAZ GARNET"), also = w("AMBER CORAL")),
        Tag("PLANET", "Planets", w("MERCURY VENUS EARTH MARS JUPITER SATURN URANUS NEPTUNE"), also = w("PLUTO")),
        Tag("METAL", "Metals", w("IRON GOLD SILVER COPPER TIN LEAD ZINC NICKEL STEEL BRASS BRONZE"), also = w("MERCURY")),
        Tag("KITCHEN", "Kitchen things", w("FORK SPOON KNIFE PLATE BOWL CUP MUG PAN POT KETTLE WHISK LADLE JUG TRAY SIEVE"), also = w("GLASS OVEN CHINA")),
        Tag("CLOTHES", "Clothes", w("SHIRT SKIRT DRESS COAT HAT SCARF GLOVE SOCK SHOE BOOT BELT TIE CAP JACKET VEST"),
            also = w("RAINCOAT OVERCOAT WAISTCOAT TAILCOAT")),
        Tag("SPORT", "Sports", w("TENNIS GOLF POLO RUGBY HOCKEY BOXING ROWING DARTS JUDO KARATE SQUASH CRICKET FOOTBALL BASEBALL BASKETBALL"),
            also = w("CHESS BOWLS SKIING DODGEBALL VOLLEYBALL NETBALL HANDBALL SOFTBALL")),
        Tag("VEG", "Vegetables", w("CARROT ONION PEA BEAN LEEK KALE CORN BEET RADISH TURNIP CELERY SQUASH PEPPER POTATO CABBAGE SPINACH"),
            also = w("GARLIC PUMPKIN TOMATO")),
        Tag("FURNITURE", "Furniture", w("CHAIR TABLE SOFA BED DESK STOOL BENCH SHELF CABINET COUCH WARDROBE"), also = w("DRESSER")),
        Tag("VEHICLE", "Vehicles", w("CAR BUS TRAIN TRAM TAXI TRUCK VAN BIKE BOAT SHIP PLANE JET FERRY YACHT CANOE SLED"), also = w("SCOOTER WARSHIP SPACESHIP AIRSHIP")),
        Tag("CHESS", "Chess pieces", w("KING QUEEN ROOK BISHOP KNIGHT PAWN")),
        Tag("BABY", "Baby animals", w("CALF FOAL LAMB CUB PUP KITTEN PUPPY CHICK PIGLET FAWN JOEY TADPOLE"), also = w("KID")),
        Tag("MONEY", "Currencies", w("DOLLAR EURO POUND YEN RUPEE PESO FRANC RAND DINAR LIRA YUAN"), also = w("WON REAL")),
        Tag("DANCE", "Dances", w("SALSA TANGO WALTZ SAMBA POLKA BALLET RUMBA DISCO JIVE FOXTROT"), also = w("TWIST")),
        Tag("HERB", "Herbs and spices", w("MINT SAGE BASIL THYME DILL PARSLEY OREGANO CUMIN CLOVE GINGER NUTMEG ROSEMARY"), also = w("PEPPER GARLIC CHIVE")),
        Tag("TIME", "Units of time", w("SECOND MINUTE HOUR DAY WEEK MONTH YEAR DECADE CENTURY")),
        Tag("TOOL", "Tools", w("HAMMER SAW DRILL WRENCH CHISEL PLIERS SPANNER AXE SPADE RAKE HOE"), also = w("FILE LEVEL RULER")),
        Tag("COUNTRY", "Countries", w("CHAD CHINA TURKEY JORDAN CUBA PERU CHILE FRANCE SPAIN ITALY JAPAN EGYPT INDIA KENYA MALI OMAN NEPAL"),
            also = w("IRAN IRAQ WALES")),
    )

    private val compounds = listOf(
        Compound("BALL", false, w("FOOT BASE BASKET SNOW FIRE EYE HAND VOLLEY NET SOFT MEAT"),
            also = w("PIN GUM CANNON ODD MOTH HAIR BLACK CURVE DODGE FAST SCREW GOLF PAINT HIGH")),
        Compound("FISH", false, w("SWORD STAR CAT GOLD JELLY SHELL MONK LION DOG SUN ANGEL"),
            also = w("CRAY BLOW FLAT CUTTLE BLUE WHITE SAIL PARROT BAT ZEBRA RED SILVER BLACK")),
        Compound("FLY", false, w("BUTTER DRAGON FIRE HORSE HOUSE MAY"), also = w("GAD SAW BLUE FRUIT GREEN BLACK SAND CRANE HOVER")),
        Compound("HOUSE", false, w("LIGHT GREEN FARM DOG TREE CLUB BOAT COURT HEN PLAY POWER WARE"),
            also = w("BIRD GATE ROAD OUT WORK GUEST HOT BATH DOLL STORE WHITE MAD COFFEE TEA ICE GLASS SUMMER")),
        Compound("BOARD", false, w("KEY SKATE SURF CARD CUP BILL DASH BLACK CHALK CLIP SNOW FLOOR"),
            also = w("SIDE SWITCH HEAD SCORE STAR SPRING OVER DART CHESS SHIP BREAD PEG PASTE WHITE")),
        Compound("CAKE", false, w("CUP PAN CHEESE SHORT FISH OAT TEA"), also = w("FRUIT PAT BEEF CRAB SPONGE HOT SEED CORN")),
        Compound("BERRY", false, w("STRAW BLUE BLACK GOOSE ELDER RASP"), also = w("CRAN BAR")),
        Compound("STONE", false, w("MILE KEY CORNER TOMB SAND LIME HAIL BIRTH FLAG HEAD MOON"),
            also = w("BRIM GALL LODE TOUCH COB GEM GRAVE BLOOD FIELD SOAP WHET GRIND CURB IRON SUN")),
        Compound("LIGHT", false, w("MOON SUN STAR FLASH SPOT HEAD TORCH CANDLE DAY FIRE LAMP FLOOD"),
            also = w("GAS HIGH SKY TWI HALF NIGHT LIME TAIL SEARCH STOP FOOT SIDE DOWN BACK")),
        Compound("WORM", false, w("EARTH SILK BOOK TAPE GLOW WOOD"), also = w("RING HOOK SLOW MEAL WIRE BLOOD HEART FLAT PIN")),
        Compound("COAT", false, w("RAIN OVER TAIL TURN WAIST UNDER TOP"), also = w("HOUSE PETTI PEA GREAT TRENCH DUST FUR FROCK")),
        Compound("BELL", false, w("BLUE DOOR DUMB COW HARE BAR"), also = w("SLEIGH CHURCH HAND")),
        Compound("WOOD", false, w("DRIFT FIRE HARD SOFT PLY RED DOG"),
            also = w("SANDAL WORM BOX HOLLY BRUSH HEART SAP DEAD ROSE IRON GREEN MATCH")),
        Compound("SHIP", false, w("FRIEND WAR SPACE HARD AIR FLAG"),
            also = w("KIN MEMBER LEADER STAR BATTLE TOWN LORD MOTHER COURT OWNER PARTNER FELLOW")),
        Compound("SUN", true, w("FLOWER RISE SET SHINE BURN DIAL LIGHT DAY SPOT BEAM ROOF BLOCK TAN FISH"),
            also = w("GLASS BATHE BED DOWN DRESS HAT LAMP DRY STROKE BURST ROOM DECK UP CREAM")),
        Compound("FIRE", true, w("WORK PLACE MAN FLY BALL WOOD ARM PROOF SIDE CRACKER WALL STORM"),
            also = w("BRAND GUARD HOUSE LIGHT POWER DOG FIGHTER BIRD TRAP WATER")),
        Compound("SNOW", true, w("MAN BALL FLAKE DROP STORM BOARD FALL PLOW SHOE DRIFT"),
            also = w("CAP LINE MOBILE BOUND SUIT FIELD BIRD PEA WHITE")),
        Compound("DOOR", true, w("BELL STEP MAT WAY KNOB MAN STOP FRAME"), also = w("KEEPER NAIL POST")),
        Compound("WATER", true, w("FALL MELON MARK PROOF SHED FRONT LILY"),
            also = w("COLOR LINE SIDE WAY BED CRESS MILL SKI POLO FOWL SPOUT TIGHT BIRD GATE WORKS")),
        Compound("STAR", true, w("FISH LIGHT DUST BOARD GAZE"), also = w("BURST SHIP FRUIT LET")),
        Compound("HAND", true, w("BAG SHAKE BALL BOOK CUFF RAIL WRITING STAND"),
            also = w("MADE SOME OUT SAW GUN SET MAID BRAKE SPRING PICK GRIP HOLD")),
        Compound("BOOK", true, w("CASE SHELF MARK WORM END KEEPER"), also = w("STORE STALL LET MAKER PLATE")),
        Compound("TOOTH", true, w("BRUSH PASTE PICK ACHE"), also = w("LESS SOME")),
        Compound("RAIN", true, w("BOW COAT DROP FALL FOREST STORM"), also = w("MAKER WATER CHECK PROOF")),
    )

    private val hidden = listOf(
        Hidden("ANIMAL", "Hidden animals", animals.filter { it.length in 3..4 }.toSet(),
            w("SCATTER LOCATE EDUCATE PIRATE SHAPE DRAPE COWARD SCOWL BOWL HOWL KNEEL WHEEL STEEL GIANT PANTRY INFANT BATH ACROBAT BATTLE " +
                "THEN KITCHEN SKEWER JEWEL CRAMP FRAME DRAMA SPIGOT MOLECULE")),
        Hidden("BODY", "Hidden body parts", w("ARM LEG HIP LIP EAR EYE TOE SHIN CHIN KNEE HAND NECK HEEL BROW JAW GUM RIB"),
            w("CHARM HARMONY ALARM LEGEND ELEGANT SHIPMENT WHIP CLIP TULIP SLIP HEARD BEARD LEARN SHINE MACHINE URCHIN SHANDY WHEEL RIBBON MISTLETOE")),
        Hidden("NUMBER", "Hidden numbers", numbers,
            w("BONE STONE DONE PHONE MONEY HONEY GONE LONELY NETWORK OFTEN TENDER STENCIL KITTEN WEIGHT FREIGHT HEIGHT CANINE")),
    )

    private val anagrams = listOf(
        Anagram("ANIMAL", "Rearrange into an animal", animals,
            w("ACT GOD ART TAR SHORE LOIN BARE HEAR REED FLOW WENT SALE TALE LATE CARB NAILS TOAST GUN SAP SPA PEA LOW TAB TOGA BALM TAN")),
    )

    val lexicon = ThreadsLexicon(tags + compounds + hidden + anagrams)
}
