package com.simplegamegen.sudoku.wordplay

/** English five-letter words for Five Letters, chosen for this app. */
object FiveWords {
    private fun w(text: String): List<String> = text.trim().split(Regex("\\s+"))

    /** Everyday words: answers on Easy and Medium. */
    val everyday: List<String> = w("""
        ABOUT ABOVE ACTOR ADULT AFTER AGAIN AGREE AHEAD ALARM ALBUM ALIVE ALLOW ALONE ALONG AMONG ANGRY ANKLE APPLE APRON ARROW
        AWAKE AWARD BACON BADGE BAKER BEACH BEARD BEGIN BELOW BENCH BERRY BIRTH BLACK BLANK BLOCK BLOOD BLOOM BOARD BONUS BRAIN
        BRAVE BREAD BREAK BRICK BRIDE BRING BROOK BROWN BRUSH BUILD BUNCH CABIN CAMEL CANDY CANOE CARRY CATCH CHAIR CHALK CHART
        CHASE CHEAP CHECK CHEEK CHEER CHESS CHEST CHICK CHILD CLEAN CLEAR CLIMB CLOCK CLOSE CLOTH CLOUD CLOWN COACH COAST COUCH
        COUNT COVER CRANE CRASH CREAM CROWD CROWN CRUMB DAISY DANCE DIARY DIRTY DIZZY DOZEN DREAM DRESS DRINK DRIVE EAGLE EARLY
        EARTH EIGHT ELBOW EMPTY ENJOY ENTER EQUAL EVERY EXTRA FAIRY FEAST FENCE FERRY FEVER FIELD FIFTH FIGHT FINAL FIRST FLAME
        FLASH FLOAT FLOOR FLOUR FLUTE FRESH FRONT FROST FRUIT FUNNY GHOST GIANT GLASS GLOBE GLOVE GRAPE GRASS GREAT GREEN GUESS
        GUEST HAPPY HEART HEAVY HELLO HONEY HORSE HOTEL HOUSE HUMAN HURRY JELLY JUICE KNIFE KNOCK LARGE LAUGH LEARN LEMON LEVEL
        LIGHT LUCKY LUNCH MAGIC MANGO MAPLE MATCH MELON MONEY MONTH MOUSE MOUTH MOVIE MUSIC NIGHT NOISE NORTH NURSE OCEAN OFTEN
        OLIVE ONION ORDER OTHER OTTER PAINT PAPER PARTY PASTA PEACE PEACH PEARL PIANO PIECE PILOT PIZZA PLACE PLANE PLANT PLATE
        POINT POWER PRIZE PUPPY QUEEN QUICK QUIET QUILT RADIO RAINY RIVER ROBIN ROBOT ROUND ROYAL RULER SALAD SAUCE SCARF SEVEN
        SHAPE SHARE SHARK SHEEP SHELF SHELL SHINE SHIRT SHORE SHORT SIGHT SKATE SKIRT SLEEP SLICE SMALL SMILE SNACK SNAKE SOUND
        SOUTH SPACE SPOON SPORT STAMP STAND START STEAM STONE STOOL STORM STORY STOVE STRAW SUGAR SUNNY SWEET SWING TABLE TASTE
        TEACH THANK THICK THING THINK THREE THROW THUMB TIGER TOAST TODAY TOOTH TORCH TOUCH TOWEL TOWER TRAIN TREAT TRUCK TULIP
        UNCLE UNDER WAGON WATCH WATER WHALE WHEAT WHEEL WHITE WORLD WRIST WRITE YOUNG ZEBRA
    """)

    /** Answers on Hard and Expert: still common, but less everyday. */
    val answers: List<String> = everyday + w("""
        ACUTE ADMIT ADOPT AGENT ALERT ALIKE ALTER ANGER ANGLE APART APPLY ARENA ARGUE ARISE ARMOR ASIDE AUDIO AVOID AWARE BASIC
        BEAST BLADE BLAME BLAST BLEND BLESS BLIND BOAST BOOST BOOTH BRAKE BRAND BRIEF BROAD BURST CABLE CARGO CAUSE CHAIN CHARM
        CHIEF CHILL CHOIR CIDER CIVIL CLAIM CLASS CLERK CLICK CLIFF COCOA CORAL COURT CRAFT CRISP CROSS CRUSH CURVE CYCLE DAILY
        DAIRY DEBUT DECAY DELAY DENSE DEPTH DINER DITCH DODGE DOUBT DOUGH DRAFT DRAIN DRAMA DRIFT DRILL DWARF EAGER ELDER ENEMY
        ENTRY ERROR EVENT EXACT EXIST FABLE FAINT FAITH FALSE FANCY FIBER FLOCK FOCUS FORCE FORTH FORUM FOUND FRAME GLORY GRACE
        GRADE GRAIN GRAND GRANT GRAPH GRASP GRAVY GREET GRILL GROUP GUARD GUIDE HABIT HARSH HEDGE HOBBY HUMOR IDEAL IMAGE INDEX
        INNER INPUT IRONY IVORY JEWEL JOINT JOLLY JUDGE KNOWN LABEL LASER LATER LAYER LEASH LEAST LEAVE LIMIT LINEN LIVER LOBBY
        LOCAL LODGE LOGIC LOOSE LOVER LOWER LOYAL MAJOR MAKER MARCH MAYOR MEDAL MERCY MERRY METAL MIGHT MINOR MINUS MIXER MODEL
        MORAL MOTOR MOUNT NERVE NEVER NOBLE NOVEL OFFER OPERA ORBIT OUNCE OUTER OWNER PANEL PATCH PEDAL PENNY PITCH PLAIN PLAZA
        POLAR PORCH POUND PRESS PRICE PRIDE PRIME PRINT PROOF PROUD PUPIL QUOTE RADAR RANCH RANGE RAPID RAVEN REACH READY REALM
        RELAX REPLY RIDER RIDGE RIGHT ROAST ROCKY ROUGH ROUTE RURAL SCALE SCENE SCENT SCOUT SCREW SHADE SHAKE SHARP SHEET SHIFT
        SHOCK SHOUT SKILL SLIDE SLOPE SMART SMOKE SOLAR SOLID SOLVE SPARE SPARK SPEAK SPEED SPELL SPEND SPICE SPINE SPRAY SQUAD
        STACK STAFF STAGE STAIR STATE STEEL STEEP STICK STILL STRIP STUDY STYLE SUPER SWAMP SWIFT SWORD THEME THIEF THIRD THORN
        TIGHT TIMER TOPIC TOTAL TOUGH TRACK TRADE TRAIL TREND TRIAL TRIBE TRICK TRULY TRUST TRUTH TWICE TWIST UNION UNITY UNTIL
        UPPER UPSET URBAN USUAL VALID VALUE VAPOR VAULT VIDEO VISIT VITAL VIVID VOICE WASTE WHERE WHILE WHOLE WIDTH WOMAN WORRY
        WORTH WOUND YACHT YIELD YOUTH
    """)

    /** Other words accepted as guesses. */
    private val extra: List<String> = w("""
        ABBEY ABIDE ABORT ABUSE ACORN ACRID ADAPT ADDED ADEPT ADORE ADORN AFOOT AGILE AGING AGONY AIDED AIMED AISLE ALGAE ALIBI
        ALIEN ALIGN ALLEY ALLOY ALOFT ALOUD ALPHA ALTAR AMBER AMBLE AMEND AMPLE AMUSE ANGEL ANNEX ANNOY ANVIL APTLY ARCED ARMED
        AROMA ASKED ASSET ATLAS ATTIC AUDIT AUNTS AVERT AWFUL AXIOM BACKS BAGEL BAGGY BALLS BALMY BANDS BANJO BANKS BARGE BARKS
        BARON BASIN BASIS BATCH BATHE BATON BEADS BEAMS BEANS BEARS BEATS BEEFY BEERS BEETS BEGAN BEGUN BEIGE BEING BELLS BELLY
        BELTS BENDS BIKES BILLS BINGO BIRDS BISON BITES BLAND BLARE BLAZE BLEAK BLEED BLIMP BLINK BLISS BLOAT BLOND BLOWN BLUES
        BLUFF BLUNT BLURT BLUSH BOATS BODES BOGUS BOILS BOLTS BONES BOOKS BOOTS BOOTY BORED BOUND BOWLS BOXER BOXES BRACE BRAID
        BRASS BRAWL BREED BRINE BRINK BRISK BROIL BROKE BROOM BROTH BUDDY BUDGE BUGGY BUGLE BULBS BULKY BULLY BUMPS BUMPY BUNNY
        BURNS BURNT BUSES BUYER BYTES CACHE CADET CAKES CALLS CALMS CAMPS CANAL CANES CAPER CARDS CARED CARES CAROL CARTS CARVE
        CASES CASTE CATER CEDAR CELLO CHAMP CHANT CHAOS CHASM CHEFS CHEWY CHIME CHIPS CHIRP CHOKE CHORD CHORE CHOSE CHUNK CHURN
        CINCH CIRCA CITED CITES CLAMP CLANG CLASH CLASP CLAWS CLING CLOAK CLONE CLUBS CLUCK CLUES CLUMP COALS COATS COBRA CODES
        COILS COINS COLDS COLON COLOR COMET COMIC COMMA CONES COOKS COPES CORDS CORES CORNS COSTS COUGH COULD COUPE COZY? CRABS
        CRACK CRAMP CRATE CRAVE CRAWL CRAZE CRAZY CREAK CREED CREEK CREEP CREPE CREST CRIED CRIES CRIME CROAK CROOK CROPS CRUDE
        CRUEL CRUST CUBES CUBIC CUPID CURLS CURLY CURRY CURSE CUTER DADDY DANDY DARED DARTS DATED DATES DEALS DEALT DEATH DECKS
        DECOY DEEDS DEITY DEMON DENIM DESKS DEVIL DIETS DIGIT DIMLY DINGY DISCO DISKS DITTO DIVER DOCKS DOING DOLLS DOMES DONOR
        DOORS DOSES DOTTY DOUSE DOWNY DOZED DRAKE DRANK DRAWL DRAWN DRAWS DREAD DRIED DRIER DRIES DRINKS DROOL DROOP DROPS DROVE
        DROWN DRUMS DRUNK DRYER DUCKS DUMMY DUNES DUSTY DUTCH DUVET DYING EARNS EASEL EATEN EATER EBONY EDGED EDGES EDICT EERIE
        EGGED EJECT ELECT ELEGY ELITE ELOPE ELUDE EMAIL EMBER EMCEE ENACT ENDED ENSUE EPOCH EQUIP ERASE ERECT ERODE ESSAY ETHIC
        EVADE EVICT EVOKE EXALT EXCEL EXERT EXILE EXPEL FACED FACES FACET FACTS FADED FAILS FAKED FALLS FARMS FATAL FAULT FAVOR
        FEARS FEEDS FEELS FEIGN FELLA FERAL FETCH FETUS FIERY FIFTY FILES FILLS FILMS FILTH FINCH FINDS FINES FIRED FIRES FIRMS
        FISHY FIXED FIXES FLAGS FLAIR FLAKE FLAKY FLANK FLAPS FLARE FLATS FLAWS FLEAS FLEET FLESH FLICK FLIES FLING FLINT FLIPS
        FLIRT FLOOD FLOPS FLORA FLOSS FLOWN FLOWS FLUFF FLUID FLUKE FLUNG FLUSH FOAMY FOGGY FOLDS FOLKS FOLLY FONTS FOODS FOOLS
        FORGE FORGO FORKS FORMS FORTY FOUND FOXES FRAIL FRAUD FREAK FREED FRIED FRIES FRILL FRISK FROGS FROWN FROZE FUDGE FUELS
        FULLY FUMES FUNDS FUNGI FUNKY FUSSY FUZZY GAINS GAMES GASES GATES GAUGE GAUZE GAVEL GAWKY GEARS GECKO GEESE GENIE GENRE
        GIFTS GIRLS GIVEN GIVES GLAND GLARE GLAZE GLEAM GLIDE GLINT GLOAT GLOOM GLOSS GLUED GNOME GOALS GOATS GOING GOODS GOOEY
        GOOSE GORGE GOWNS GRABS GRAIL GRATE GRAVE GREED GRIEF GRIME GRIMY GRIND GRINS GRIPE GRIPS GROAN GROOM GROSS GROWL GROWN
        GROWS GRUEL GRUFF GRUNT GUILD GUILT GUISE GULLS GUMMY GUSTS GUTSY GYPSY HABIT HAIRS HAIRY HALLS HALVE HANDS HANDY HANGS
        HARDY HAREM HARMS HATCH HATED HATES HAUNT HAVEN HAVOC HAWKS HAZEL HEADS HEADY HEALS HEAPS HEARD HEARS HEATS HEAVE HEDGE
        HEELS HEFTY HEIST HELIX HELPS HENCE HERBS HERDS HERON HIKED HIKER HILLS HINGE HINTS HIPPO HIRED HITCH HOARD HOIST HOLDS
        HOLES HOLLY HOMES HOOKS HOPED HOPES HORNS HOSTS HOUND HOURS HOVER HOWLS HUMID HUMPS HUNCH HUNKS HUNTS HUSKY HYENA HYMNS
        ICING ICONS IDEAS IDIOM IDIOT IDLED IGLOO IMPLY INEPT INFER INGOT INLET IRATE IRONS ISSUE ITCHY ITEMS JACKS JAILS JAUNT
        JEANS JERKS JERKY JESTS JIFFY JOINS JOKED JOKER JOKES JOUST JUMBO JUMPS JUMPY JUROR KARMA KAYAK KEBAB KEEPS KETCH KEYED
        KICKS KIDDO KILLS KINDA KINDS KINGS KIOSK KITES KITTY KNACK KNEAD KNEEL KNEES KNELT KNITS KNOBS KNOTS KNOWS KOALA LABOR
        LACED LACES LADDER LADEN LADLE LAKES LAMBS LAMPS LANCE LANDS LANES LANKY LAPSE LARVA LATCH LATTE LAWNS LEADS LEAFY LEAKS
        LEAKY LEANT LEAPS LEAPT LEASE LEDGE LEECH LEGAL LEMUR LENDS LIARS LIFTS LIKED LIKES LILAC LIMBS LIMES LINED LINER LINES
        LINKS LIONS LISTS LITER LIVED LIVES LLAMA LOADS LOANS LOBES LOCKS LOCUS LOFTY LOGIN LONER LONGS LOOKS LOOMS LOOPS LORDS
        LOSER LOSES LOTUS LOUSY LOVED LOVES LUNAR LUNGE LURCH LURED LURKS LYING LYRIC MACHO MAIDS MAILS MAINS MAKES MALES MALLS
        MANIA MANOR MARCH MARKS MARRY MARSH MASKS MATES MATHS MEALS MEANS MEANT MEATS MEATY MEETS MELTS MEMOS MENUS MERIT MESSY
        METER MICRO MIDST MILES MILKY MILLS MIMIC MINCE MINDS MINED MINER MINES MINTS MISTY MITTS MOANS MOATS MOCKS MODEM MOIST
        MOLAR MOLDS MOLDY MOODY MOONS MOOSE MOPED MORPH MOSSY MOTEL MOTHS MOTTO MOULD MOVED MOVER MOVES MUDDY MUGGY MULCH MUMMY
        MUNCH MURAL MURKY MUSHY MUTED MYTHS NAILS NAIVE NAMED NAMES NANNY NASAL NASTY NAVAL NEATH NEEDS NEEDY NEIGH NERDY NESTS
        NEWER NEWLY NICER NICHE NIECE NINJA NINTH NODES NOISY NOMAD NOOSE NOTCH NOTED NOTES NUDGE NUTTY NYLON OASIS OBESE OCCUR
        ODDER ODDLY OFFAL OILED OLDER OMEGA OPENS OPTIC ORGAN OTHER OUGHT OUNCE OUTDO OVENS OVERT OWING OWNED OXIDE OZONE PACED
        PACES PACKS PAGES PAINS PAIRS PALMS PANDA PANIC PANTS PARKS PARSE PARTS PASTE PASTY PATIO PAUSE PAVED PAWNS PAYEE PEAKS
        PEARS PECAN PEELS PEERS PENAL PERCH PERIL PERKY PESKY PESTS PETAL PETTY PHASE PHONE PHOTO PICKS PICKY PIERS PIGGY PILES
        PILLS PINCH PINES PINKS PINTS PIPES PIQUE PIXEL PLAID PLANS PLAYS PLEAD PLEAT PLOTS PLUCK PLUGS PLUMB PLUME PLUMP PLUMS
        PLUNK PLUSH POEMS POETS POKED POKER POLES POLKA POLLS PONDS POOLS POPPY PORES PORTS POSED POSER POSES POSSE POSTS POUCH
        POUTS PRANK PRAWN PRAYS PREEN PRESS PREYS PRICK PRIED PRIES PRISM PRIVY PROBE PRONE PRONG PROPS PROSE PROWL PRUNE PSALM
        PUFFY PULLS PULPY PULSE PUMPS PUNCH PUNKS PURGE PURSE PUSHY QUACK QUAIL QUAKE QUALM QUART QUASI QUEEN QUERY QUEST QUEUE
        QUIRK QUOTA RACER RACES RACKS RAFTS RAGED RAIDS RAILS RAINS RAISE RAKED RALLY RAMPS RANKS RASPY RATED RATES RATIO RAYON
        RAZOR READS REALM REAMS REARS REBEL RECAP REEFS REELS REFER REHAB REIGN REINS RENEW RENTS REPAY RERUN RESET RESIN RETRO
        RHINO RHYME RICER RIDES RIFLE RIFTS RINGS RINSE RIPEN RISEN RISES RISKS RISKY RIVAL ROADS ROARS ROBES ROCKS RODEO ROLES
        ROLLS ROOFS ROOMS ROOMY ROOTS ROPES ROSES ROTOR ROUSE ROWDY RUDER RUGBY RUINS RULED RULES RUMOR RUNGS RUNNY RUSTY SADLY
        SAFER SAILS SAINT SALES SALON SALSA SALTY SANDS SANDY SATIN SAUNA SAVED SAVES SAVOR SAVVY SCALD SCALP SCALY SCAMP SCANS
        SCARE SCARY SCONE SCOOP SCOOT SCOPE SCORE SCORN SCRAP SCRUB SEALS SEAMS SEATS SEEDS SEEKS SEEMS SEIZE SELLS SENDS SENSE
        SERUM SERVE SETUP SEWER SHACK SHAFT SHALL SHAME SHAWL SHEAR SHEDS SHIED SHINY SHIPS SHOAL SHOES SHONE SHOOK SHOOT SHOPS
        SHOVE SHOWN SHOWS SHOWY SHRUB SHRUG SHUCK SHUNT SIDES SIEGE SIEVE SIGHS SIGNS SILKY SILLY SINCE SINGS SINKS SIREN SITES
        SIXTH SIXTY SIZED SIZES SKIES SKIMP SKINS SKIPS SKULL SKUNK SLABS SLACK SLAIN SLANG SLANT SLAPS SLASH SLATE SLAVE SLEEK
        SLEET SLEPT SLIME SLIMY SLING SLINK SLIPS SLOTH SLOTS SLUMP SLUNG SLUSH SMACK SMASH SMEAR SMELL SMELT SMIRK SMITH SMOKY
        SNAIL SNAPS SNARE SNARL SNEAK SNEER SNIFF SNIPE SNOOP SNORE SNORT SNOUT SNOWY SNUCK SOAPY SOBER SOCKS SOFAS SOFTY SOGGY
        SOLES SONAR SONGS SONIC SORRY SORTS SOULS SOUPS SOUPY SPADE SPANS SPASM SPAWN SPEAR SPECK SPENT SPIED SPIES SPIKE SPILL
        SPILT SPINS SPIRE SPITE SPLIT SPOIL SPOKE SPOOF SPOOK SPOOL SPOTS SPOUT SPREE SPRIG SPUNK SPURS SPURT SQUAT SQUID STABS
        STAIN STAKE STALE STALK STALL STANK STARE STARK STARS STAYS STEAK STEAL STEEP STEER STEMS STEPS STERN STEWS STIFF STING
        STINK STINT STOCK STOIC STOKE STOLE STOMP STOOD STOOP STOPS STORE STORK STOUT STRAP STRAY STREW STRUM STRUT STUCK STUFF
        STUMP STUNG STUNK STUNT SUAVE SUEDE SUITE SUITS SULKY SUNNY SURGE SUSHI SWABS SWAMP SWANS SWAPS SWARM SWEAR SWEAT SWEEP
        SWELL SWEPT SWIMS SWINE SWIPE SWIRL SWOON SWOOP SYRUP TABBY TACKS TACKY TACOS TAFFY TAILS TAKEN TAKES TALES TALKS TALLY
        TALON TANGO TANGY TANKS TAPED TAPES TARDY TARTS TASKS TASTY TAUNT TAXES TAXIS TEAMS TEARS TEARY TEASE TEDDY TEENS TEETH
        TELLS TEMPO TENDS TENOR TENSE TENTH TENTS TERMS TESTS TEXTS THAWS THEFT THEIR THERE THESE THIGH THOSE TIARA TIDAL TIDES
        TILED TILES TILTS TIMID TIPSY TIRED TIRES TITAN TITLE TOADS TOKEN TONAL TONED TONES TONGS TONIC TOOLS TOPAZ TORSO TOTEM
        TOURS TOWNS TOXIC TRACE TRAMP TRAPS TRASH TRAYS TREAD TREES TREKS TRIED TRIES TRIMS TRIOS TRIPE TRIPS TRITE TROLL TROOP
        TROUT TRUCE TRUMP TRUNK TUBES TUCKS TUMMY TUNED TUNER TUNES TUNIC TURNS TUSKS TUTOR TWANG TWEAK TWEED TWEET TWINE TWINS
        TWIRL UDDER ULCER ULTRA UMBRA UNCUT UNDID UNDUE UNFIT UNLIT UNSET UNTIE UNWED USAGE USHER USING UTTER VAGUE VALET VALVE
        VANES VASES VEGAN VEILS VEINS VENOM VENUE VERBS VERGE VERSE VERVE VESTS VIEWS VIGIL VILLA VINES VINYL VIOLA VIPER VIRAL
        VIRUS VISOR VISTA VOCAL VODKA VOGUE VOTED VOTER VOTES VOUCH VOWED VOWEL WADED WAFER WAGED WAGES WAILS WAIST WAITS WAIVE
        WAKEN WALKS WALLS WALTZ WANTS WARDS WARMS WARNS WARTS WASPS WAVED WAVES WAXED WEARY WEAVE WEDGE WEEDS WEEDY WEEKS WEEPY
        WEIGH WEIRD WELLS WELSH WENCH WHACK WHEEZE WHIFF WHIMS WHINE WHINY WHIPS WHIRL WHISK WIDEN WIDER WIDOW WIELD WILDS WIMPY
        WINCE WINCH WINDS WINDY WINES WINGS WINKS WIPED WIPER WIPES WIRED WIRES WISER WITCH WITTY WIVES WOKEN WOLVES WOMEN WOODS
        WOODY WOOLY WORDS WORDY WORKS WORMS WORSE WORST WOULD WOVEN WRATH WRECK WRING WRONG WROTE YARDS YARNS YAWNS YEARN YEARS
        YEAST YELLS YOLKS YUMMY ZESTY ZONES
    """).filter { it.length == 5 && it.all { c -> c in 'A'..'Z' } }

    /** Every accepted guess. */
    val valid: Set<String> = (answers + extra).toSet()

    init {
        require(everyday.all { it.length == 5 && it.all { c -> c in 'A'..'Z' } } && answers.toSet().size == answers.size) { "bad Five Letters answers" }
    }
}
