package com.simplegamegen.sudoku.wordplay

/**
 * Cryptogram sayings. Only proverbs and public-domain sources: pre-1900 authors,
 * the King James Bible and U.S. government speeches.
 */
internal object Quotes {
    val all: List<Pair<String, String>> = listOf(
        "Well done is better than well said." to "Benjamin Franklin",
        "Lost time is never found again." to "Benjamin Franklin",
        "Energy and persistence conquer all things." to "Benjamin Franklin",
        "Little strokes fell great oaks." to "Benjamin Franklin",
        "A word to the wise is enough." to "Benjamin Franklin",
        "The early morning has gold in its mouth." to "Benjamin Franklin",
        "Early to bed and early to rise makes a man healthy, wealthy and wise." to "Benjamin Franklin",
        "In this world nothing can be said to be certain, except death and taxes." to "Benjamin Franklin",
        "Wise men don't need advice. Fools won't take it." to "Benjamin Franklin",
        "Slow and steady wins the race." to "Aesop",
        "Look before you leap." to "Aesop",
        "Little by little does the trick." to "Aesop",
        "Don't count your chickens before they are hatched." to "Aesop",
        "The course of true love never did run smooth." to "William Shakespeare",
        "All the world's a stage." to "William Shakespeare",
        "Brevity is the soul of wit." to "William Shakespeare",
        "We know what we are, but know not what we may be." to "William Shakespeare",
        "Nothing will come of nothing." to "William Shakespeare",
        "All that glisters is not gold." to "William Shakespeare",
        "Be not afraid of greatness." to "William Shakespeare",
        "Parting is such sweet sorrow." to "William Shakespeare",
        "Uneasy lies the head that wears a crown." to "William Shakespeare",
        "The fault, dear Brutus, is not in our stars, but in ourselves." to "William Shakespeare",
        "Nothing great was ever achieved without enthusiasm." to "Ralph Waldo Emerson",
        "The only way to have a friend is to be one." to "Ralph Waldo Emerson",
        "Hitch your wagon to a star." to "Ralph Waldo Emerson",
        "Heaven is under our feet as well as over our heads." to "Henry David Thoreau",
        "Our life is frittered away by detail. Simplify, simplify." to "Henry David Thoreau",
        "Knowledge is power." to "Francis Bacon",
        "Hope is the thing with feathers." to "Emily Dickinson",
        "It was the best of times, it was the worst of times." to "Charles Dickens",
        "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife." to "Jane Austen",
        "Call me Ishmael." to "Herman Melville",
        "Tis better to have loved and lost than never to have loved at all." to "Alfred Tennyson",
        "Hope springs eternal in the human breast." to "Alexander Pope",
        "To err is human, to forgive divine." to "Alexander Pope",
        "Fools rush in where angels fear to tread." to "Alexander Pope",
        "A thing of beauty is a joy for ever." to "John Keats",
        "Beauty is truth, truth beauty." to "John Keats",
        "Water, water, every where, nor any drop to drink." to "Samuel Taylor Coleridge",
        "I wandered lonely as a cloud." to "William Wordsworth",
        "The pen is mightier than the sword." to "Edward Bulwer-Lytton",
        "Whatever is worth doing at all is worth doing well." to "Lord Chesterfield",
        "The unexamined life is not worth living." to "Socrates",
        "Four score and seven years ago our fathers brought forth on this continent a new nation." to "Abraham Lincoln",
        "The only thing we have to fear is fear itself." to "Franklin D. Roosevelt",
        "Ask not what your country can do for you, ask what you can do for your country." to "John F. Kennedy",
        "Speak softly and carry a big stick." to "Theodore Roosevelt",
        "A merry heart doeth good like a medicine." to "Proverbs 17:22",
        "Pride goeth before destruction, and an haughty spirit before a fall." to "Proverbs 16:18",
        "The race is not to the swift, nor the battle to the strong." to "Ecclesiastes 9:11",
        "To every thing there is a season, and a time to every purpose under the heaven." to "Ecclesiastes 3:1",
        "Fortune favors the bold." to "Proverb",
        "Where there is a will, there is a way." to "Proverb",
        "Actions speak louder than words." to "Proverb",
        "The early bird catches the worm." to "Proverb",
        "Every cloud has a silver lining." to "Proverb",
        "Practice makes perfect." to "Proverb",
        "Rome was not built in a day." to "Proverb",
        "Two heads are better than one." to "Proverb",
        "Many hands make light work." to "Proverb",
        "A stitch in time saves nine." to "Proverb",
        "Still waters run deep." to "Proverb",
        "Honesty is the best policy." to "Proverb",
        "When in Rome, do as the Romans do." to "Proverb",
        "Necessity is the mother of invention." to "Proverb",
        "Laughter is the best medicine." to "Proverb",
        "He who hesitates is lost." to "Proverb",
        "Better late than never." to "Proverb",
        "A picture is worth a thousand words." to "Proverb",
        "You can't judge a book by its cover." to "Proverb",
        "Birds of a feather flock together." to "Proverb",
        "Absence makes the heart grow fonder." to "Proverb",
        "A friend in need is a friend indeed." to "Proverb",
        "Time and tide wait for no man." to "Proverb",
        "Great oaks from little acorns grow." to "Proverb",
        "Even a stopped clock is right twice a day." to "Proverb",
        "Do not put off till tomorrow what you can do today." to "Proverb",
        "A journey of a thousand miles begins with a single step." to "Proverb",
        "The squeaky wheel gets the grease." to "Proverb",
    )
}

/** Public count for the collection guide. */
object QuotesInfo { val count: Int get() = Quotes.all.size }
